name: Deploy Now
on:
  push:
	    branches:
			      - main
						  workflow_dispatch:
							jobs:
							  build:
								    runs-on: ubuntu-latest
										    steps:
												      - uses: actions/checkout@v4
															      - uses: actions/setup-node@v4
																		        with:
																						          node-version: 20
																											      - run: npm install
																														      - run: npm run build
																																	      - uses: ionos-deploy-now/deploy-now-action@v2
																																				        with:
																																								          api-key: ${{ secrets.IONOS_API_KEY }}
																																													          project-id: ${{ secrets.IONOS_PROJECT_ID }}
																																																		          service-host: ${{ secrets.IONOS_SERVICE_HOST }}
																																																							
